server:
  port: 30001

spring:
  application:
    name: provider-application
  cloud:
    pipi:
      discovery:
        serverAddr: localhost:50001
        service: ${spring.application.name}
        port: ${server.port}
    service-registry:
      auto-registration:
        enabled: true
    sentinel:
      eager: true
      transport:
        dashboard: localhost:8080
        port: 8720

#management:
#  endpoint:
#    sentinel:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: '*'

feign:
  sentinel:
    enabled: true # 激活S
